import { muscle } from '../nodeHelpers';

const ATLAS_CTX = {
  whyItMatters: 'Fills out the full-body atlas so regional study structures read in context.',
  commonMistake: 'Study this structure in its module tab for drawing notes and reps.',
  movementEffect: 'Visible in Full body view only — switch to the matching region to drill it.',
};

/** Extra Z-Anatomy muscles for Full body atlas (not in module quiz decks). */
export const atlasSupplementNodes = [
  muscle(
    'muscle_gluteus_maximus',
    'Gluteus maximus',
    'leg',
    0,
    'egg',
    ATLAS_CTX,
    { atlasOnly: true, cameraPresetKey: 'pelvis' },
  ),
  muscle(
    'muscle_gluteus_medius',
    'Gluteus medius',
    'leg',
    1,
    'egg',
    ATLAS_CTX,
    { atlasOnly: true, cameraPresetKey: 'pelvis' },
  ),
  muscle(
    'muscle_gluteus_minimus',
    'Gluteus minimus',
    'leg',
    2,
    'egg',
    ATLAS_CTX,
    { atlasOnly: true, cameraPresetKey: 'pelvis' },
  ),
  muscle(
    'muscle_piriformis',
    'Piriformis',
    'leg',
    2,
    'egg',
    ATLAS_CTX,
    { atlasOnly: true, cameraPresetKey: 'pelvis' },
  ),
  muscle(
    'muscle_iliacus',
    'Iliacus',
    'leg',
    2,
    'egg',
    ATLAS_CTX,
    { atlasOnly: true, cameraPresetKey: 'pelvis' },
  ),
  muscle(
    'muscle_vastus_intermedius',
    'Vastus intermedius',
    'leg',
    2,
    'egg',
    ATLAS_CTX,
    { atlasOnly: true, cameraPresetKey: 'leg' },
  ),
  muscle(
    'muscle_soleus',
    'Soleus',
    'leg',
    1,
    'egg',
    ATLAS_CTX,
    { atlasOnly: true, cameraPresetKey: 'leg' },
  ),
  muscle(
    'muscle_vastus_medialis',
    'Vastus medialis',
    'leg',
    0,
    'egg',
    ATLAS_CTX,
    { atlasOnly: true, cameraPresetKey: 'leg' },
  ),
  muscle(
    'muscle_gracilis',
    'Gracilis',
    'leg',
    1,
    'egg',
    ATLAS_CTX,
    { atlasOnly: true, cameraPresetKey: 'leg' },
  ),
  muscle(
    'muscle_adductor_longus',
    'Adductor longus',
    'leg',
    1,
    'egg',
    ATLAS_CTX,
    { atlasOnly: true, cameraPresetKey: 'leg' },
  ),
  muscle(
    'muscle_semitendinosus',
    'Semitendinosus',
    'leg',
    0,
    'egg',
    ATLAS_CTX,
    { atlasOnly: true, cameraPresetKey: 'leg' },
  ),
  muscle(
    'muscle_semimembranosus',
    'Semimembranosus',
    'leg',
    1,
    'egg',
    ATLAS_CTX,
    { atlasOnly: true, cameraPresetKey: 'leg' },
  ),
  muscle(
    'muscle_sartorius',
    'Sartorius',
    'leg',
    0,
    'egg',
    ATLAS_CTX,
    { atlasOnly: true, cameraPresetKey: 'leg' },
  ),
  muscle(
    'muscle_tensor_fasciae_latae',
    'Tensor fasciae latae',
    'leg',
    0,
    'egg',
    ATLAS_CTX,
    { atlasOnly: true, cameraPresetKey: 'pelvis' },
  ),
  muscle(
    'muscle_teres_major',
    'Teres major',
    'shoulder_neck',
    1,
    'egg',
    ATLAS_CTX,
    { atlasOnly: true, cameraPresetKey: 'back' },
  ),
  muscle(
    'muscle_infraspinatus',
    'Infraspinatus',
    'shoulder_neck',
    2,
    'egg',
    ATLAS_CTX,
    { atlasOnly: true, cameraPresetKey: 'back' },
  ),
  muscle(
    'muscle_supraspinatus',
    'Supraspinatus',
    'shoulder_neck',
    2,
    'egg',
    ATLAS_CTX,
    { atlasOnly: true, cameraPresetKey: 'shoulder' },
  ),
  muscle(
    'muscle_rhomboid_major',
    'Rhomboid major',
    'shoulder_neck',
    1,
    'egg',
    ATLAS_CTX,
    { atlasOnly: true, cameraPresetKey: 'back' },
  ),
  muscle(
    'muscle_splenius_capitis',
    'Splenius capitis',
    'shoulder_neck',
    1,
    'egg',
    ATLAS_CTX,
    { atlasOnly: true, cameraPresetKey: 'head' },
  ),
  muscle(
    'muscle_omohyoid',
    'Omohyoid',
    'shoulder_neck',
    1,
    'egg',
    ATLAS_CTX,
    { atlasOnly: true, cameraPresetKey: 'head' },
  ),
];
