import type { StanzaSong, StanzaStemTrack } from '../db/stanzaDb';
import { stanzaDb } from '../db/stanzaDb';
import { computeStanzaLocalMediaFingerprint } from '../utils/stanzaLocalMediaFingerprint';
import {
  readStanzaDriveTombstones,
  type StanzaDriveTombstone,
} from './stanzaDriveTombstones';
import {
  readStanzaYoutubeTombstones,
  type StanzaYoutubeTombstone,
} from './stanzaYoutubeTombstones';

export const STANZA_DRIVE_APP_ID = 'stanza' as const;

/** Stem labels and mix settings only — blobs stay on device. */
export type StanzaStemDriveRow = Omit<StanzaStemTrack, 'localBlob'>;

/**
 * Drive envelope row. Blob fields are dropped from JSON because they are huge; mix-layer
 * audio is stored as separate Drive files under `stem_audio/` (`stems[].driveFileId` in
 * `progress.json`). Main recording bytes live under `main_audio/` and are linked via each row's
 * `driveSourceFileId` in `progress.json` after the first successful backup.
 *   - Or they're cheaply re-derivable on the destination device (`localVideoThumbnailBlob` is
 *     auto-generated by `stanzaVideoThumbnail.ts` from the local video). Keeping them in the
 *     envelope would JSON-stringify a `Blob` to `"{}"`, polluting Drive with empty objects and
 *     wasting bytes.
 */
export type StanzaSongDriveRow = Omit<
  StanzaSong,
  'localAudioBlob' | 'localVideoThumbnailBlob' | 'stems'
> & {
  stems?: StanzaStemDriveRow[];
};

function songWithoutBlob(row: StanzaSong): StanzaSongDriveRow {
  const { localAudioBlob, localVideoThumbnailBlob, stems, analysisCache, ...rest } = row;
  void localAudioBlob;
  void localVideoThumbnailBlob;
  void analysisCache;
  const fingerprint =
    rest.localMediaFingerprint ??
    (localAudioBlob
      ? computeStanzaLocalMediaFingerprint({ sizeBytes: localAudioBlob.size, fileName: row.title })
      : undefined);
  const base = fingerprint ? { ...rest, localMediaFingerprint: fingerprint } : rest;
  if (!stems?.length) return base as StanzaSongDriveRow;
  const stemMeta: StanzaStemDriveRow[] = stems.map(({ localBlob, ...m }) => {
    void localBlob;
    return m;
  });
  return { ...base, stems: stemMeta };
}

export interface StanzaDriveEnvelopeV1 {
  schemaVersion: 1;
  exportedAt: string;
  app: typeof STANZA_DRIVE_APP_ID;
  /** Song metadata only; local audio blobs and practice takes are not included. */
  songs: StanzaSongDriveRow[];
  /**
   * Per-`driveSourceFileId` deletion markers — the user explicitly removed these Drive-backed
   * library rows. Other devices pulling this envelope union the list into their own tombstone
   * store and skip remote rows whose `driveSourceFileId` appears here (see
   * [ADR 0006](../../../docs/adr/0006-stanza-drive-backup-merge-and-restore.md)). Optional so
   * older Stanza builds that don't write this field still parse; an absent field is treated as
   * the empty set.
   */
  deletedDriveSourceFileIds?: StanzaDriveTombstone[];
  /** YouTube video ids the user removed — optional for back-compat. */
  deletedYoutubeVideoIds?: StanzaYoutubeTombstone[];
}

export async function buildStanzaDriveEnvelope(): Promise<StanzaDriveEnvelopeV1> {
  const rows = await stanzaDb.songs.toArray();
  const songs: StanzaSongDriveRow[] = rows.map(songWithoutBlob);
  const deletedDriveSourceFileIds = readStanzaDriveTombstones();
  const deletedYoutubeVideoIds = readStanzaYoutubeTombstones();
  const env: StanzaDriveEnvelopeV1 = {
    schemaVersion: 1,
    exportedAt: new Date().toISOString(),
    app: STANZA_DRIVE_APP_ID,
    songs,
  };
  if (deletedDriveSourceFileIds.length > 0) {
    env.deletedDriveSourceFileIds = deletedDriveSourceFileIds;
  }
  if (deletedYoutubeVideoIds.length > 0) {
    env.deletedYoutubeVideoIds = deletedYoutubeVideoIds;
  }
  return env;
}

export function serializeStanzaDriveEnvelope(envelope: StanzaDriveEnvelopeV1): string {
  return JSON.stringify(envelope);
}

function parseTombstones(raw: unknown): StanzaDriveTombstone[] {
  if (!Array.isArray(raw)) return [];
  const out: StanzaDriveTombstone[] = [];
  for (const item of raw) {
    if (!item || typeof item !== 'object') continue;
    const o = item as { fileId?: unknown; removedAt?: unknown };
    if (typeof o.fileId !== 'string' || !o.fileId.trim()) continue;
    if (typeof o.removedAt !== 'string') continue;
    out.push({ fileId: o.fileId.trim(), removedAt: o.removedAt });
  }
  return out;
}

export function parseStanzaDriveEnvelope(json: string): StanzaDriveEnvelopeV1 {
  const data = JSON.parse(json) as Partial<StanzaDriveEnvelopeV1>;
  if (data.schemaVersion !== 1) throw new Error('Unsupported Stanza backup version.');
  if (data.app !== STANZA_DRIVE_APP_ID) throw new Error('This backup is not from Stanza.');
  if (!Array.isArray(data.songs)) throw new Error('Backup has no songs array.');
  if (typeof data.exportedAt !== 'string') throw new Error('Backup is missing a timestamp.');
  const env: StanzaDriveEnvelopeV1 = {
    schemaVersion: 1,
    exportedAt: data.exportedAt,
    app: STANZA_DRIVE_APP_ID,
    songs: data.songs,
  };
  const tombstones = parseTombstones(data.deletedDriveSourceFileIds);
  if (tombstones.length > 0) env.deletedDriveSourceFileIds = tombstones;
  return env;
}
