import { fetchYoutubeOembedMeta } from '../youtube/youtubeOembedMeta';
import { youtubeWatchUrlFromInput } from '../youtube/parseYoutubeVideoUrl';
import { inferDefaultResourceLabelFromUrl, isAutoGeneratedResourceLabel, patchResourceLabel } from './encoreResourceLinks';
import type { EncoreMiscResource } from '../types';

/**
 * Best-effort remote title for a pasted reference URL (YouTube oEmbed today).
 * Returns null when no better title is available — callers keep the sync default label.
 */
export async function resolveEncoreResourceLabel(url: string): Promise<string | null> {
  const trimmed = url.trim();
  if (!trimmed) return null;

  const watchUrl = youtubeWatchUrlFromInput(trimmed);
  if (watchUrl) {
    const meta = await fetchYoutubeOembedMeta(watchUrl);
    const title = meta?.title?.trim();
    if (title) return title;
  }

  const fallback = inferDefaultResourceLabelFromUrl(trimmed);
  return fallback || null;
}

/** Replace auto-generated nicknames when a remote title resolves (YouTube, etc.). */
export function scheduleEncoreResourceLabelEnrichment(
  url: string,
  resourceId: string,
  getResources: () => EncoreMiscResource[],
  onChange: (resources: EncoreMiscResource[]) => void,
): void {
  void resolveEncoreResourceLabel(url).then((label) => {
    const trimmed = label?.trim();
    if (!trimmed) return;
    const cur = getResources();
    const resource = cur.find((entry) => entry.id === resourceId);
    const resourceUrl = resource?.url?.trim();
    if (!resource || !resourceUrl) return;
    if (!isAutoGeneratedResourceLabel(resource.label, resourceUrl)) return;
    if (trimmed === resource.label) return;
    onChange(patchResourceLabel(cur, resourceId, trimmed));
  });
}
