import { describe, expect, it } from 'vitest';
import {
  createResourceFromUrl,
  inferDefaultResourceLabelFromUrl,
  isAutoGeneratedResourceLabel,
} from './encoreResourceLinks';

describe('inferDefaultResourceLabelFromUrl', () => {
  it('names Google Docs without using the full URL', () => {
    expect(
      inferDefaultResourceLabelFromUrl(
        'https://docs.google.com/document/d/abc123/edit?tab=t.0',
      ),
    ).toBe('Google Doc');
  });

  it('uses hostname for generic links', () => {
    expect(inferDefaultResourceLabelFromUrl('https://www.example.com/path')).toBe('example.com');
  });
});

describe('createResourceFromUrl', () => {
  it('defaults link label to inferred name, not raw URL', () => {
    const resource = createResourceFromUrl(
      'https://docs.google.com/document/d/abc123/edit',
    );
    expect(resource?.label).toBe('Google Doc');
    expect(resource?.url).toContain('docs.google.com');
  });

  it('respects an explicit nickname', () => {
    const resource = createResourceFromUrl('https://example.com', 'My notes');
    expect(resource?.label).toBe('My notes');
  });
});

describe('isAutoGeneratedResourceLabel', () => {
  it('detects raw URL and inferred defaults', () => {
    const url = 'https://docs.google.com/document/d/x/edit';
    expect(isAutoGeneratedResourceLabel(url, url)).toBe(true);
    expect(isAutoGeneratedResourceLabel('Google Doc', url)).toBe(true);
    expect(isAutoGeneratedResourceLabel('My draft', url)).toBe(false);
  });
});
