export const BEAT_ANALYSIS_SCHEMA_VERSION = 'beat-analysis-v1';
export const BEAT_ANALYSIS_ENGINE_VERSION = 'engine-2026-03-22';

export const BEAT_ANALYSIS_VERSION = `${BEAT_ANALYSIS_SCHEMA_VERSION}:${BEAT_ANALYSIS_ENGINE_VERSION}`;
