import { test, expect } from '@playwright/test';
import { statSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const COMPLEX_RHYTHM =
  'D-T-K-S-D-T-K-S-D-T-K-S-D-T-K-S|D-T-K-S-D-T-K-S-D-T-K-S-D-T-K-S|'
  + 'D-T-K-S-D-T-K-S-D-T-K-S-D-T-K-S|D-T-K-S-D-T-K-S-D-T-K-S-D-T-K-S|'
  + 'D-T-K-S-D-T-K-S-D-T-K-S-D-T-K-S|D-T-K-S-D-T-K-S-D-T-K-S-D-T-K-S|'
  + 'D-T-K-S-D-T-K-S-D-T-K-S-D-T-K-S|D-T-K-S-D-T-K-S-D-T-K-S-D-T-K-S';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_DIR = join(__dirname, 'drums-score-export.spec.ts-snapshots');

test.describe('Darbuka score export', () => {
  test('PNG export saves a non-trivial score snapshot', async ({ page }) => {
    await page.goto('/drums/');
    const input = page.getByPlaceholder('D-T-__T-D---T---');
    await expect(input).toBeVisible({ timeout: 10_000 });
    await input.fill(COMPLEX_RHYTHM);
    await input.blur();
    await expect(page.locator('.vexflow-container svg')).toBeVisible({ timeout: 20_000 });

    await page.getByRole('button', { name: /Download rhythm/i }).click();
    await page.getByRole('radio', { name: 'PNG' }).check();

    const downloadPromise = page.waitForEvent('download', { timeout: 30_000 });
    await page.getByRole('button', { name: /^Export$/ }).click();
    const download = await downloadPromise;

    mkdirSync(OUTPUT_DIR, { recursive: true });
    const pngPath = join(OUTPUT_DIR, 'score-export-verify.png');
    await download.saveAs(pngPath);

    expect(statSync(pngPath).size).toBeGreaterThan(10_000);
    expect(download.suggestedFilename()).toMatch(/\.png$/i);
    writeFileSync(join(OUTPUT_DIR, 'README.txt'), `Generated by drums-score-export.spec.ts\n${pngPath}\n`);
  });
});
