import type { Stage } from './types';

/**
 * The canonical stage progression for every exercise.
 * Each stage builds on the previous one pedagogically.
 */
export function buildStages(exerciseId: string): Stage[] {
  return [
    {
      id: `${exerciseId}-s1`,
      stageNumber: 1,
      label: 'Right hand — free tempo',
      hand: 'right',
      useTempo: false,
      bpm: 0,
      useMetronome: false,
      subdivision: 'none',
      mutePlayback: false,
    },
    {
      id: `${exerciseId}-s2`,
      stageNumber: 2,
      label: 'Left hand — free tempo',
      hand: 'left',
      useTempo: false,
      bpm: 0,
      useMetronome: false,
      subdivision: 'none',
      mutePlayback: false,
    },
    {
      id: `${exerciseId}-s3`,
      stageNumber: 3,
      label: 'Right hand — slow tempo',
      hand: 'right',
      useTempo: true,
      bpm: 52,
      useMetronome: true,
      subdivision: 'none',
      mutePlayback: false,
    },
    {
      id: `${exerciseId}-s4`,
      stageNumber: 4,
      label: 'Left hand — slow tempo',
      hand: 'left',
      useTempo: true,
      bpm: 52,
      useMetronome: true,
      subdivision: 'none',
      mutePlayback: false,
    },
    {
      id: `${exerciseId}-s5`,
      stageNumber: 5,
      label: 'Both hands — slow tempo',
      hand: 'both',
      useTempo: true,
      bpm: 52,
      useMetronome: true,
      subdivision: 'none',
      mutePlayback: false,
    },
    {
      id: `${exerciseId}-s6`,
      stageNumber: 6,
      label: 'Both hands — moderate tempo',
      hand: 'both',
      useTempo: true,
      bpm: 72,
      useMetronome: true,
      subdivision: 'none',
      mutePlayback: false,
    },
    {
      id: `${exerciseId}-s7`,
      stageNumber: 7,
      label: 'Both hands — no playback',
      hand: 'both',
      useTempo: true,
      bpm: 72,
      useMetronome: true,
      subdivision: 'none',
      mutePlayback: true,
    },
    {
      id: `${exerciseId}-s8`,
      stageNumber: 8,
      label: 'Both hands — target tempo',
      hand: 'both',
      useTempo: true,
      bpm: 92,
      useMetronome: true,
      subdivision: 'none',
      mutePlayback: true,
    },
    {
      id: `${exerciseId}-s9`,
      stageNumber: 9,
      label: 'Both hands — eighth subdivision',
      hand: 'both',
      useTempo: true,
      bpm: 72,
      useMetronome: true,
      subdivision: 'eighth',
      mutePlayback: true,
    },
    {
      id: `${exerciseId}-s10`,
      stageNumber: 10,
      label: 'Both hands — sixteenth subdivision',
      hand: 'both',
      useTempo: true,
      bpm: 60,
      useMetronome: true,
      subdivision: 'sixteenth',
      mutePlayback: true,
    },
  ];
}
