import type { Stage } from './types';

/**
 * The canonical stage progression for every exercise.
 * Each stage builds on the previous one pedagogically.
 */
export function buildStages(exerciseId: string): Stage[] {
  return [
    {
      id: `${exerciseId}-s1`,
      stageNumber: 1,
      label: 'Right hand — free tempo',
      description: 'Play the scale with your right hand using the fingerings shown. Go at whatever pace feels comfortable — focus on hitting the right notes with the right fingers.',
      hand: 'right',
      useTempo: false,
      bpm: 0,
      useMetronome: false,
      subdivision: 'none',
      mutePlayback: false,
    },
    {
      id: `${exerciseId}-s2`,
      stageNumber: 2,
      label: 'Left hand — free tempo',
      description: 'Now play the scale with your left hand. Take your time with the fingering — the thumb-under and finger-over crossings are the trickiest part.',
      hand: 'left',
      useTempo: false,
      bpm: 0,
      useMetronome: false,
      subdivision: 'none',
      mutePlayback: false,
    },
    {
      id: `${exerciseId}-s3`,
      stageNumber: 3,
      label: 'Right hand — slow tempo',
      description: 'Play the scale in time with the metronome. The metronome will count you in with 4 clicks, then try to land each note right on the beat.',
      hand: 'right',
      useTempo: true,
      bpm: 52,
      useMetronome: true,
      subdivision: 'none',
      mutePlayback: false,
    },
    {
      id: `${exerciseId}-s4`,
      stageNumber: 4,
      label: 'Left hand — slow tempo',
      description: 'Same slow tempo, now with your left hand. Keep your wrist relaxed and let the metronome guide your pace.',
      hand: 'left',
      useTempo: true,
      bpm: 52,
      useMetronome: true,
      subdivision: 'none',
      mutePlayback: false,
    },
    {
      id: `${exerciseId}-s5`,
      stageNumber: 5,
      label: 'Both hands — slow tempo',
      description: 'Play the scale with both hands together. Both hands play the same notes in different octaves. Start slowly and focus on keeping them synchronized.',
      hand: 'both',
      useTempo: true,
      bpm: 52,
      useMetronome: true,
      subdivision: 'none',
      mutePlayback: false,
    },
    {
      id: `${exerciseId}-s6`,
      stageNumber: 6,
      label: 'Both hands — moderate tempo',
      description: 'Picking up the pace! Play with both hands at a moderate tempo. If you feel tension, slow down your movements — speed comes from relaxation.',
      hand: 'both',
      useTempo: true,
      bpm: 72,
      useMetronome: true,
      subdivision: 'none',
      mutePlayback: false,
    },
    {
      id: `${exerciseId}-s7`,
      stageNumber: 7,
      label: 'Both hands — no guide',
      description: 'The guide notes are off — play from memory while the metronome keeps time. You know this scale; trust your fingers.',
      hand: 'both',
      useTempo: true,
      bpm: 72,
      useMetronome: true,
      subdivision: 'none',
      mutePlayback: true,
    },
    {
      id: `${exerciseId}-s8`,
      stageNumber: 8,
      label: 'Both hands — target tempo',
      description: 'Full speed! Play the scale at the target tempo from memory. Aim for evenness — every note should have the same duration and volume.',
      hand: 'both',
      useTempo: true,
      bpm: 92,
      useMetronome: true,
      subdivision: 'none',
      mutePlayback: true,
    },
    {
      id: `${exerciseId}-s9`,
      stageNumber: 9,
      label: 'Both hands — eighth note subdivision',
      description: 'Play two notes per beat (eighth notes). This trains your inner sense of rhythm. Feel the subdivision between each metronome click.',
      hand: 'both',
      useTempo: true,
      bpm: 72,
      useMetronome: true,
      subdivision: 'eighth',
      mutePlayback: true,
    },
    {
      id: `${exerciseId}-s10`,
      stageNumber: 10,
      label: 'Both hands — sixteenth note subdivision',
      description: 'Four notes per beat! This is advanced rhythmic control. Stay relaxed and let the notes flow evenly between the clicks.',
      hand: 'both',
      useTempo: true,
      bpm: 60,
      useMetronome: true,
      subdivision: 'sixteenth',
      mutePlayback: true,
    },
  ];
}
