import type { AnatomyTerm, AnatomyTermLesson } from '../types/anatomyTerm';

export const ANATOMY_TERMS: AnatomyTerm[] = [
  {
    id: 'term_anatomical_position',
    label: 'Anatomical position',
    category: 'reference_pose',
    definition:
      'Standing upright, feet together, arms at the sides, palms facing forward. Directional terms assume this pose.',
    example: 'Palms face forward, not the thighs.',
    visualization: 'text_only',
  },
  {
    id: 'term_planes_overview',
    label: 'Body planes',
    category: 'plane',
    definition:
      'Three reference planes slice the body: sagittal (left–right), coronal (front–back), and transverse (upper–lower).',
    visualization: 'planes_overview',
  },
  {
    id: 'term_plane_sagittal',
    label: 'Sagittal plane',
    category: 'plane',
    definition: 'Vertical plane that splits the body into left and right halves.',
    visualization: 'plane_sagittal',
  },
  {
    id: 'term_plane_coronal',
    label: 'Coronal plane',
    category: 'plane',
    definition: 'Vertical plane that splits the body into front (anterior) and back (posterior).',
    visualization: 'plane_coronal',
  },
  {
    id: 'term_plane_transverse',
    label: 'Transverse plane',
    category: 'plane',
    definition: 'Horizontal plane that splits the body into upper and lower parts.',
    visualization: 'plane_transverse',
  },
  {
    id: 'term_anterior',
    label: 'Anterior',
    category: 'location',
    definition: 'Toward the front of the body (toward the face in anatomical position).',
    oppositeTermId: 'term_posterior',
    example: 'The sternum is anterior to the spine.',
    visualization: 'direction_arrow',
    direction: 'anterior',
    exampleNodeIds: ['bone_sternum'],
  },
  {
    id: 'term_posterior',
    label: 'Posterior',
    category: 'location',
    definition: 'Toward the back of the body.',
    oppositeTermId: 'term_anterior',
    example: 'The scapula is posterior on the rib cage.',
    visualization: 'direction_arrow',
    direction: 'posterior',
    exampleNodeIds: ['bone_scapula'],
  },
  {
    id: 'term_medial',
    label: 'Medial',
    category: 'location',
    definition: 'Toward the midline of the body.',
    oppositeTermId: 'term_lateral',
    example: 'The nose is medial to the eyes.',
    visualization: 'direction_arrow',
    direction: 'medial',
  },
  {
    id: 'term_lateral',
    label: 'Lateral',
    category: 'location',
    definition: 'Away from the midline, toward the side.',
    oppositeTermId: 'term_medial',
    example: 'The deltoid cap is lateral on the arm.',
    visualization: 'direction_arrow',
    direction: 'lateral',
    exampleNodeIds: ['muscle_deltoid_lateral'],
  },
  {
    id: 'term_superior',
    label: 'Superior',
    category: 'location',
    definition: 'Toward the head, above another structure.',
    oppositeTermId: 'term_inferior',
    example: 'The skull is superior to the rib cage.',
    visualization: 'direction_arrow',
    direction: 'superior',
    exampleNodeIds: ['bone_skull'],
  },
  {
    id: 'term_inferior',
    label: 'Inferior',
    category: 'location',
    definition: 'Toward the feet, below another structure.',
    oppositeTermId: 'term_superior',
    example: 'The pelvis is inferior to the rib cage.',
    visualization: 'direction_arrow',
    direction: 'inferior',
    exampleNodeIds: ['bone_pelvis'],
  },
  {
    id: 'term_proximal',
    label: 'Proximal',
    category: 'location',
    definition: 'Closer to the trunk or point of attachment (limbs).',
    oppositeTermId: 'term_distal',
    example: 'The shoulder is proximal to the elbow.',
    visualization: 'direction_arrow',
    direction: 'proximal',
    exampleNodeIds: ['bone_humerus'],
  },
  {
    id: 'term_distal',
    label: 'Distal',
    category: 'location',
    definition: 'Farther from the trunk or attachment (limbs).',
    oppositeTermId: 'term_proximal',
    example: 'The hand is distal to the forearm.',
    visualization: 'direction_arrow',
    direction: 'distal',
  },
  {
    id: 'term_deep',
    label: 'Deep',
    category: 'location',
    definition: 'Closer to the center of the body or farther under other muscles — not closer to the skin.',
    oppositeTermId: 'term_superficial',
    example: 'Brachialis sits deep to biceps brachii.',
    visualization: 'example_highlight',
    exampleNodeIds: ['muscle_brachialis'],
  },
  {
    id: 'term_superficial',
    label: 'Superficial',
    category: 'location',
    definition: 'Closer to the skin surface.',
    oppositeTermId: 'term_deep',
    example: 'The rectus abdominis is superficial on the front torso.',
    visualization: 'example_highlight',
    exampleNodeIds: ['muscle_rectus_abdominis'],
  },
  {
    id: 'term_flexion',
    label: 'Flexion',
    category: 'movement',
    definition: 'Bending that decreases the angle between two parts.',
    oppositeTermId: 'term_extension',
    example: 'Elbow flexion brings the forearm toward the upper arm.',
    visualization: 'joint_motion',
    exampleNodeIds: ['joint_elbow'],
  },
  {
    id: 'term_extension',
    label: 'Extension',
    category: 'movement',
    definition: 'Straightening that increases the angle between two parts.',
    oppositeTermId: 'term_flexion',
    example: 'Knee extension straightens the leg.',
    visualization: 'joint_motion',
    exampleNodeIds: ['joint_knee'],
  },
  {
    id: 'term_abduction',
    label: 'Abduction',
    category: 'movement',
    definition: 'Movement away from the midline.',
    oppositeTermId: 'term_adduction',
    example: 'Raising the arm to the side is shoulder abduction.',
    visualization: 'joint_motion',
    exampleNodeIds: ['muscle_deltoid_lateral'],
  },
  {
    id: 'term_adduction',
    label: 'Adduction',
    category: 'movement',
    definition: 'Movement toward the midline.',
    oppositeTermId: 'term_abduction',
    example: 'Lowering the arm back to the hip is adduction.',
    visualization: 'joint_motion',
  },
  {
    id: 'term_pronation',
    label: 'Pronation',
    category: 'movement',
    definition: 'Rotating the forearm so the palm faces posteriorly (down when arms forward).',
    oppositeTermId: 'term_supination',
    example: 'Typing on a keyboard uses pronation.',
    visualization: 'joint_motion',
    exampleNodeIds: ['bone_radius', 'bone_ulna'],
  },
  {
    id: 'term_supination',
    label: 'Supination',
    category: 'movement',
    definition: 'Rotating the forearm so the palm faces anteriorly (up when arms forward).',
    oppositeTermId: 'term_pronation',
    example: 'Holding a bowl of soup uses supination.',
    visualization: 'joint_motion',
  },
  {
    id: 'term_origin',
    label: 'Origin',
    category: 'attachment',
    definition: 'Muscle attachment on the more fixed bone (moves little when the muscle contracts).',
    oppositeTermId: 'term_insertion',
    example: 'The lat origin spans the spine and pelvis.',
    visualization: 'text_only',
    exampleNodeIds: ['muscle_latissimus_dorsi'],
  },
  {
    id: 'term_insertion',
    label: 'Insertion',
    category: 'attachment',
    definition: 'Muscle attachment on the bone that moves when the muscle pulls.',
    oppositeTermId: 'term_origin',
    example: 'The biceps inserts on the radius.',
    visualization: 'text_only',
    exampleNodeIds: ['muscle_biceps_brachii'],
  },
  {
    id: 'term_prefix_bi',
    label: 'Bi- (two)',
    category: 'naming_prefix',
    definition: 'Prefix meaning two heads or parts.',
    example: 'Biceps brachii has two heads.',
    visualization: 'term_pattern_highlight',
    exampleNodeIds: ['muscle_biceps_brachii'],
  },
  {
    id: 'term_prefix_tri',
    label: 'Tri- (three)',
    category: 'naming_prefix',
    definition: 'Prefix meaning three heads or parts.',
    example: 'Triceps brachii (arm) and triceps surae (calf) both use tri-.',
    visualization: 'term_pattern_highlight',
    exampleNodeIds: ['muscle_triceps_long_head'],
  },
  {
    id: 'term_prefix_maximus',
    label: 'Maximus (largest)',
    category: 'naming_prefix',
    definition: 'Suffix for the largest muscle in a group.',
    example: 'Gluteus maximus is the biggest glute.',
    visualization: 'term_pattern_highlight',
    exampleNodeIds: ['muscle_gluteus_maximus'],
  },
  {
    id: 'term_prefix_minimus',
    label: 'Minimus (smallest)',
    category: 'naming_prefix',
    definition: 'Suffix for the smallest muscle in a group.',
    example: 'Gluteus minimus is the smallest glute.',
    visualization: 'term_pattern_highlight',
    exampleNodeIds: ['muscle_gluteus_minimus'],
  },
  {
    id: 'term_prefix_longus',
    label: 'Longus (long)',
    category: 'naming_prefix',
    definition: 'Suffix for the long variant in a muscle set.',
    example: 'Adductor longus is the long adductor of the thigh.',
    visualization: 'term_pattern_highlight',
  },
  {
    id: 'term_prefix_brevis',
    label: 'Brevis (short)',
    category: 'naming_prefix',
    definition: 'Suffix for the short variant in a muscle set.',
    example: 'Adductor brevis is shorter than adductor longus.',
    visualization: 'term_pattern_highlight',
  },
  {
    id: 'term_prefix_gluteus',
    label: 'Gluteus',
    category: 'naming_prefix',
    definition: 'Buttock muscles — maximus, medius, and minimus stack from large to small.',
    visualization: 'term_pattern_highlight',
  },
  {
    id: 'term_joint_hinge',
    label: 'Hinge joint',
    category: 'joint_type',
    definition: 'Synovial joint that bends on one axis — flexion and extension only.',
    example: 'Elbow and knee are hinge joints.',
    visualization: 'joint_type_highlight',
    exampleNodeIds: ['joint_elbow', 'joint_knee', 'joint_ankle'],
  },
  {
    id: 'term_joint_ball_socket',
    label: 'Ball & socket joint',
    category: 'joint_type',
    definition: 'Synovial joint with the widest range — flexion, extension, abduction, adduction, and rotation.',
    example: 'Shoulder and hip are ball-and-socket joints.',
    visualization: 'joint_type_highlight',
    exampleNodeIds: ['joint_shoulder', 'joint_hip'],
  },
  {
    id: 'term_joint_pivot',
    label: 'Pivot joint',
    category: 'joint_type',
    definition: 'Synovial joint that rotates around one long axis.',
    example: 'Forearm pronation and supination use pivot joints at the radius and ulna.',
    visualization: 'joint_type_highlight',
    exampleNodeIds: ['joint_proximal_radioulnar'],
  },
  {
    id: 'term_joint_ellipsoid',
    label: 'Ellipsoid joint',
    category: 'joint_type',
    definition: 'Oval ball-and-socket joint — two axes of motion, no full rotation.',
    example: 'The wrist (radiocarpal joint) is an ellipsoid joint.',
    visualization: 'joint_type_highlight',
    exampleNodeIds: ['joint_wrist'],
  },
  {
    id: 'term_joint_saddle',
    label: 'Saddle joint',
    category: 'joint_type',
    definition: 'Both bones have a concave and convex face that fit together — strong thumb mobility.',
    example: 'The thumb carpometacarpal joint is a saddle joint.',
    visualization: 'joint_type_highlight',
    exampleNodeIds: ['joint_sternoclavicular', 'joint_thumb_cmc'],
  },
  {
    id: 'term_joint_plane',
    label: 'Plane joint',
    category: 'joint_type',
    definition: 'Flat surfaces that glide or rotate slightly — often in rows of small bones.',
    example: 'Carpals and tarsals form plane joints.',
    visualization: 'joint_type_highlight',
    exampleNodeIds: ['joint_intercarpal', 'joint_acromioclavicular', 'joint_subtalar'],
  },
];

export const ANATOMY_TERM_BY_ID = new Map(ANATOMY_TERMS.map((t) => [t.id, t]));

export function getAnatomyTermById(id: string): AnatomyTerm | undefined {
  return ANATOMY_TERM_BY_ID.get(id);
}

export const ANATOMY_TERM_LESSONS: AnatomyTermLesson[] = [
  {
    id: 'terms_intro',
    title: 'Reference & planes',
    steps: [
      { termId: 'term_anatomical_position', coachLine: 'All directions start from this pose.' },
      { termId: 'term_planes_overview', coachLine: 'Tap a plane on the model to name it.' },
      { termId: 'term_plane_sagittal', coachLine: 'Left–right slices.' },
      { termId: 'term_plane_coronal', coachLine: 'Front–back slices.' },
      { termId: 'term_plane_transverse', coachLine: 'Upper–lower slices.' },
    ],
  },
  {
    id: 'terms_location',
    title: 'Location pairs',
    steps: [
      { termId: 'term_anterior', coachLine: 'Toward the front.' },
      { termId: 'term_posterior', coachLine: 'Toward the back.' },
      { termId: 'term_medial', coachLine: 'Toward the midline.' },
      { termId: 'term_lateral', coachLine: 'Toward the side.' },
      { termId: 'term_superior', coachLine: 'Toward the head.' },
      { termId: 'term_inferior', coachLine: 'Toward the feet.' },
      { termId: 'term_proximal', coachLine: 'Closer to the trunk on a limb.' },
      { termId: 'term_distal', coachLine: 'Farther from the trunk.' },
      { termId: 'term_deep', coachLine: 'Under other muscles — not the same as inferior.' },
      { termId: 'term_superficial', coachLine: 'Closer to the skin.' },
    ],
  },
  {
    id: 'terms_movement',
    title: 'Movement',
    steps: [
      { termId: 'term_flexion', coachLine: 'Watch the angle close at the elbow.' },
      { termId: 'term_extension', coachLine: 'The angle opens.' },
      { termId: 'term_abduction', coachLine: 'Away from the midline.' },
      { termId: 'term_adduction', coachLine: 'Back toward the midline.' },
      { termId: 'term_pronation', coachLine: 'Palm turns down or back.' },
      { termId: 'term_supination', coachLine: 'Palm turns up or forward.' },
      { termId: 'term_origin', coachLine: 'The stable attachment.' },
      { termId: 'term_insertion', coachLine: 'The attachment that moves.' },
    ],
  },
  {
    id: 'terms_naming',
    title: 'Naming patterns',
    steps: [
      { termId: 'term_prefix_bi', coachLine: 'Matching muscles highlight on the model.' },
      { termId: 'term_prefix_tri', coachLine: 'Tri- marks three-headed muscles.' },
      { termId: 'term_prefix_maximus', coachLine: 'Maximus = largest in the set.' },
      { termId: 'term_prefix_minimus', coachLine: 'Minimus = smallest in the set.' },
      { termId: 'term_prefix_longus', coachLine: 'Longus = the long variant.' },
      { termId: 'term_prefix_brevis', coachLine: 'Brevis = the short variant.' },
      { termId: 'term_prefix_gluteus', coachLine: 'Gluteus muscles share this root.' },
    ],
  },
  {
    id: 'terms_joints',
    title: 'Joint types',
    steps: [
      { termId: 'term_joint_hinge', coachLine: 'One axis — flexion and extension.' },
      { termId: 'term_joint_pivot', coachLine: 'Rotation on one long axis.' },
      { termId: 'term_joint_ball_socket', coachLine: 'Widest range of motion.' },
      { termId: 'term_joint_ellipsoid', coachLine: 'Two axes, no full spin.' },
      { termId: 'term_joint_saddle', coachLine: 'Concave + convex faces fit together.' },
      { termId: 'term_joint_plane', coachLine: 'Gliding flat surfaces.' },
    ],
  },
];

export const TERMS_GATE_REPS = 3;

export function getAllTermIds(): string[] {
  return ANATOMY_TERMS.map((t) => t.id);
}

export function getTermsGateIds(): string[] {
  return [
    'term_anatomical_position',
    'term_plane_sagittal',
    'term_anterior',
    'term_posterior',
    'term_medial',
    'term_lateral',
    'term_flexion',
    'term_extension',
  ];
}
