name: CI/CD

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.ts'
      - '**.tsx' 
      - '**.js'
      - '**.jsx'
      - '**.json'
      - 'package*.json'
      - '.github/workflows/**'
      - 'vite.config.*'
      - 'vitest.config.*'
      - 'tsconfig*.json'
      - 'eslint.config.*'
      - 'knip.config.*'
  pull_request:
    branches: [ main, master ]
    paths:
      - '**.ts'
      - '**.tsx'
      - '**.js' 
      - '**.jsx'
      - '**.json'
      - 'package*.json'
      - '.github/workflows/**'
      - 'vite.config.*'
      - 'vitest.config.*'
      - 'tsconfig*.json'
      - 'eslint.config.*'
      - 'knip.config.*'

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      CI: true
      NODE_ENV: test
      HUSKY: 0
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        # Temporarily disable cache to rule out cache issues
        # cache: 'npm'
        
    - name: Verify environment
      run: |
        node --version
        npm --version
        
    - name: Install dependencies
      run: |
        # Apply Rollup fix for Linux binary dependencies
        rm -rf node_modules package-lock.json
        npm install
        npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Check for dead code
      run: npm run knip
      
    - name: Run tests
      run: npm test
      
    - name: Build project
      run: npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        # Apply Rollup fix for Linux binary dependencies
        rm -rf node_modules package-lock.json
        npm install
        npm ci
        
    - name: Build project
      run: npm run build
      
    - name: Setup Pages
      uses: actions/configure-pages@v5
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 