name: Minimal Test

on:
  push:
    branches: [ main ]

jobs:
  minimal-test:
    runs-on: ubuntu-latest
    
    env:
      CI: true
      NODE_ENV: test
      HUSKY: 0
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Show environment
      run: |
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Working directory: $(pwd)"
        echo "Files in current directory:"
        ls -la
        echo "Package.json exists:"
        cat package.json | head -20
        
    - name: Install dependencies (CI method)
      run: |
        rm -rf node_modules
        npm ci --verbose
      
    - name: Test each CI step individually
      run: |
        echo "=== Testing npm scripts one by one ==="
        
        echo "1. Testing lint..."
        npm run lint || echo "LINT FAILED with exit code $?"
        
        echo "2. Testing build..."
        npm run build || echo "BUILD FAILED with exit code $?"
        
        echo "3. Testing npm test..."
        npm test || echo "TEST FAILED with exit code $?"
        
        echo "=== All steps attempted ===" 