name: Simple CI

on:
  push:
    branches: [ main ]

jobs:
  simple-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Show current directory and files
      run: |
        echo "Current directory: $(pwd)"
        echo "Files in root:"
        ls -la
        echo "Files in src:"
        ls -la src/ || echo "No src directory"
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Run linter  
      run: npm run lint
      
    - name: Build project
      run: |
        echo "Creating dist directory..."
        mkdir -p dist
        npm run build 